Name:           ros-kinetic-roseus-tutorials
Version:        1.6.3
Release:        0%{?dist}
Summary:        ROS roseus_tutorials package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/roseus_tutorials
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-ar-track-alvar
Requires:       ros-kinetic-checkerboard-detector
Requires:       ros-kinetic-image-proc
Requires:       ros-kinetic-image-view2
Requires:       ros-kinetic-jsk-recognition-msgs
Requires:       ros-kinetic-opencv-apps
Requires:       ros-kinetic-posedetection-msgs
Requires:       ros-kinetic-pr2eus
Requires:       ros-kinetic-visualization-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-roseus
BuildRequires:  ros-kinetic-rostest

%description
roseus_tutorials

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Sep 08 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.6.3-0
- Autogenerated by Bloom

* Thu Jun 22 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.6.2-0
- Autogenerated by Bloom

* Wed Mar 15 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.6.1-0
- Autogenerated by Bloom

* Sat Mar 11 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.6.0-3
- Autogenerated by Bloom

