Name:           ros-jade-roseus-tutorials
Version:        1.6.1
Release:        0%{?dist}
Summary:        ROS roseus_tutorials package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/roseus_tutorials
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-ar-track-alvar
Requires:       ros-jade-checkerboard-detector
Requires:       ros-jade-image-proc
Requires:       ros-jade-image-view2
Requires:       ros-jade-jsk-recognition-msgs
Requires:       ros-jade-opencv-apps
Requires:       ros-jade-posedetection-msgs
Requires:       ros-jade-pr2eus
Requires:       ros-jade-visualization-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-roseus
BuildRequires:  ros-jade-rostest

%description
roseus_tutorials

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed Mar 15 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.6.1-0
- Autogenerated by Bloom

* Sat Mar 11 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.6.0-2
- Autogenerated by Bloom

